runtime: python
env: flex
entrypoint: python main.py
runtime_config:
    python_version: 3
network:
  instance_tag: test-py-server
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.85
  target_concurrent_requests: 100